# Generated by Django 4.2.7 on 2024-10-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('availability_status', models.BooleanField(default=True)),
                ('owner', models.UUIDField()),
            ],
        ),
    ]
