# Generated by Django 4.2.7 on 2023-11-30 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gst', models.CharField(max_length=15)),
                ('otp', models.BigIntegerField(blank=True, null=True)),
                ('push_notification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('user_registered', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
