# Generated by Django 4.2.7 on 2024-10-15 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.BigIntegerField(blank=True, null=True)),
                ('reading_preferences', models.TextField(blank=True)),
                ('favorite_genres', models.CharField(blank=True, max_length=255)),
                ('email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('user_registered', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
