# Generated by Django 4.2.7 on 2024-10-15 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('initiator', models.UUIDField()),
                ('acceptor', models.UUIDField()),
                ('initiator_book_id', models.UUIDField()),
                ('acceptor_book_id', models.UUIDField()),
                ('created_on', models.BigIntegerField()),
                ('delivery_method', models.CharField(max_length=255)),
                ('exchange_duration', models.IntegerField()),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=10)),
            ],
        ),
    ]
